name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./premake5.exe gmake2
    - name: make
      run: make ./build/Makefile config=debug_win64 all
