name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: configure
      run: ./premake5.exe vs2022
    - name: build project
      run: msbuild build/gta2ue.sln -p:Configuration="Debug" -p:Platform="Win64"
